services:
  app:
    image: ${PROJECT_NAME}-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-app
    environment:
      - PHP_WORKER_INSTALL_BCMATH=true
      - XDEBUG_MODE=off
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - internal
    depends_on:
      - mysql # или pgsql

  web:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-web
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./../:/var/www
      - ./docker/nginx:/etc/nginx/conf.d # Здесь должен лежать ваш nginx-конфиг
      - ./logs/nginx:/var/log/nginx # Логи для поддоменов
    depends_on:
      - app
    networks:
      - internal

  mysql:
    image: mysql:latest
    container_name: ${PROJECT_NAME}-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}' # Используем переменную из .env
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql-data:/var/lib/mysql' # Для сохранения данных
      - ./docker/mysql:/docker-entrypoint-initdb.d # Для SQL-скриптов при инициализации
    ports:
      - '${DB_PORT}:3306'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

#    pgsql:
#        image: postgres:latest
#        container_name: ${PROJECT_NAME}-pgsql
#        env_file:
#            - .env
#        environment:
#            PGPASSWORD: '${DB_PASSWORD}'
#            POSTGRES_DB: '${DB_DATABASE}'
#            POSTGRES_USER: '${DB_USERNAME}'
#            POSTGRES_PASSWORD: '${DB_PASSWORD}'
#        volumes:
#            - ./docker/pgsql:/tmp
#            - 'pg-data:/var/lib/postgresql/data'
#        ports:
#            - '${DB_PORT}:5432'
#        networks:
#            - internal

volumes:
  mysql-data:
    driver: local
#    pg-data:
#        driver: local
networks:
  internal:
    driver: bridge
